name: Security Audit

on:
  schedule:
    - cron: "0 9 * * 1" # 每周一上午运行
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  workflow_dispatch:

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rust-lang/audit@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
